customhost = "employee.cfg0bodzn4uw.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chongjunwei-employee"
customregion = "us-east-1"
